server:
  port: 8189

#测试 serverTimezone=UTC jdbc:mysql://192.168.79.67:3306/dafa-cloud?serverTimezone=UTC
spring:
  datasource:
    local:
      username: root
      password: 123456
      jdbc-url: jdbc:mysql://localhost:3306/dafa-cloud?serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource

    dev1:
#      username: root
#      password: 123456
      #widows
#      jdbc-url: jdbc:mysql://192.168.79.67:3306/dafa-cloud?serverTimezone=UTC
      #本地
#      jdbc-url: jdbc:mysql://127.0.0.1:3306/dafa-cloud?serverTimezone=UTC
      username: test-web
      password: ms168169
      jdbc-url: jdbc:mysql://tester.cluster-cmysgwjezdbr.ap-southeast-1.rds.amazonaws.com?useSSL=false&characterEncoding=utf8
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource

    proBetting:
      username: us31jw9
      password: KzrdFtgXILlE
      jdbc-url: jdbc:mysql://18.139.94.243:8312?useSSL=false&characterEncoding=utf8
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource


    initial-size: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 6000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    #filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  redis:
    host: 18.162.190.99
    port: 6381

mybatis-plus:
  global-config:
    db-config:
      db-type: MYSQL
      capital-mode: false #开启大写命名
      column-like: true #开启 LIKE 查询



#mybatis 打印sql日志
#logging:
#  level:
#    pers.dafacloud.mapper: debug
#    com.dafacloud.management.managementapi.mapping: debug

